# Generated by Django 2.2.9 on 2020-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=31)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
