# Generated by Django 2.2.9 on 2020-12-08 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteGame',
            fields=[
                ('parent_game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='choice', serialize=False, to='engine_refactored.Game')),
                ('chosen_set_index', models.IntegerField()),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
